### ISSUE TITLE
Requesting passwords not possible if user is on Server 2019

### ISSUE THREAD

**Issue by mrmueller** [lithnet/laps-web#19]
Hi, 

Thanks for this great tool, we are using it with success :)

There seems to be a problem tough, if the web interface is called from IE on a Windows Server 2019.
The request does not end up in the logs or in event viewer. There is just the error in the web interface which you can see below. Let me know if you need more information.

Thanks

![laps2](https://user-images.githubusercontent.com/9515311/70324912-0d127900-1831-11ea-9499-55b90366bc4f.png)

![server 2019](https://user-images.githubusercontent.com/9515311/70324838-d63c6300-1830-11ea-82a9-2aca837eced8.png)

![IE](https://user-images.githubusercontent.com/9515311/70324840-d6d4f980-1830-11ea-9639-73d2a5856722.png)

**Comment by ryannewington** [comment]
Very strange, let me look into this further

**Comment by ryannewington** [comment]
@mrmueller I can't seem to reproduce this. IE11 on Windows Server 2019 is working for me. Is there anything else about the environment that you can tell me to help reproduce what you are seeing?

When does the error appear?

**Comment by ryannewington** [comment]
@mrmueller Just checking in to see if you are you still having this issue?

**Comment by mrmueller** [comment]
@ryannewington sorry for the delay. I'm not sure what happened but we are no longer able to reproduce the issue. Closing

Sorry again.

**Comment by sceptapular** [comment]
Same issue here; unrelated to the browser though.  Using WS2019 for the IIS server.  Same issue whether testing on the server itself or via a member PC's browser.  First time trying this.

**Comment by sceptapular** [comment]
An unhandled error occurred while processing the request for the password for *computername* by user unknown
System.Runtime.InteropServices.COMException (0x8007200A): The specified directory service attribute or value does not exist.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_SchemaEntry()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.IsContainer(DirectoryEntry de)
   at System.DirectoryServices.AccountManagement.ADStoreCtx..ctor(DirectoryEntry ctxBase, Boolean ownCtxBase, String username, String password, ContextOptions options)
   at System.DirectoryServices.AccountManagement.PrincipalContext.CreateContextFromDirectoryEntry(DirectoryEntry entry)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Lithnet.Laps.Web.Controllers.LapController.GetCurrentUser() in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 222
   at Lithnet.Laps.Web.Controllers.LapController.Get(LapRequestModel model) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 43

**Comment by ryannewington** [comment]
Moved to #43
