### ISSUE TITLE
Authentication ADFS : IDX10214: Audience validation failed

### ISSUE THREAD

**Issue by njd90** [lithnet/laps-web#2]
Hello,

I try ADFS authentification but i got an error 
`
The authentication provider returned an error
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'https://laps.utbm.fr'. Did not match: validationParameters.ValidAudience: 'https://laps.utbm.fr/' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateConditions(SamlSecurityToken securityToken, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.Owin.Security.WsFederation.WsFederationAuthenticationHandler.<AuthenticateCoreAsync>d__1f.MoveNext()
`

In web.config, I added this  :
`    <add key="owin:appStartup" value="Lithnet.Laps.Web.Startup.ConfigureWsFederation" />
    <add key="ida:wtrealm" value="https://laps.utbm.fr/" />
    <add key="ida:metadata" value="https://adfs.utbm.fr/FederationMetadata/2007-06/FederationMetadata.xml" />`

In IIS, Anonymous authentication is enabled, and all other options are disabled.
![image](https://user-images.githubusercontent.com/5481030/46413361-0b2ac280-c721-11e8-8c6f-909e1f330677.png)

For ADFS configuration : 
![image](https://user-images.githubusercontent.com/5481030/46413456-3dd4bb00-c721-11e8-95a5-f740e78f1236.png)

![image](https://user-images.githubusercontent.com/5481030/46413440-331a2600-c721-11e8-93b2-b20815d05b83.png)

![image](https://user-images.githubusercontent.com/5481030/46413490-55ac3f00-c721-11e8-9098-e9e7e192c12b.png)

Can you help me ?

**Comment by ryannewington** [comment]
Hi.

I think the audience must match exactly. Drop the trailing slash from the config version, or add it to the ADFS.

Audiences: '**https://laps.utbm.fr<---**'. 
Did not match: validationParameters.ValidAudience: '**https://laps.utbm.fr/<----** '

**Comment by njd90** [comment]
Hi,

Thanks, it's work.
