### ISSUE TITLE
Your request could not be processed because your SSO identity could not be found in the directory

### ISSUE THREAD

**Issue by dr-raypc** [lithnet/laps-web#32]
Hello Ryan,

I followed your documentation and setup MFA with our Azure Active Directory. When signing in and accepting the MFA pop up, I receive the following error message: "An authentication error occurred : Your request could not be processed because your SSO identity could not be found in the directory"

How can I solve this?

**Comment by ryannewington** [comment]
Hi @dr-raypc 

This usually means that the UPN claim is not being sent from the idp. 

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims

**Comment by dr-raypc** [comment]
Thank you for that information, Ryan! I was able to bypass that error message however now I receive an "Access Denied" error when attempting to view LAPS passwords inside a testing OU.

I read through the documentation and verified my config file is correct. Any idea why I am receiving this access denied error?

I noticed I do not have a D drive set on this machine and cannot locate the script shown in the error message.


An unhandled error occurred while processing the request for the password for <RETRACTED> by user <RETRACTED>
System.UnauthorizedAccessException: Access is denied.

   at System.DirectoryServices.Interop.UnsafeNativeMethods.IAds.SetInfo()
   at System.DirectoryServices.DirectoryEntry.CommitChanges()
   at Lithnet.Laps.Web.Controllers.LapController.SetExpiryTime(DirectoryEntry d, DateTime newDateTime) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 285
   at Lithnet.Laps.Web.Controllers.LapController.UpdateTargetPasswordExpiry(TargetElement target, ComputerPrincipal computer) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 278
   at Lithnet.Laps.Web.Controllers.LapController.Get(LapRequestModel model) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 101

**Comment by dr-raypc** [comment]
Disregard --- It appears the service account did not get configured properly (missed " at end of DSCALS command).

I appreciate all of your help, Ryan!

**Comment by ryannewington** [comment]
Hey @dr-raypc 

Were you able to get this working?
