### ISSUE TITLE
COM Exception Error

### ISSUE THREAD

**Issue by simonford99** [lithnet/laps-web#42]
Hi

I am getting the following error. I have checked the service account and this can read LAPS passwords and write a new expiry date.

Any ideas?

2021-01-01 10:47:04.0777| INFO|xxxx has requested the password for EDNDWX004463
2021-01-01 10:47:04.1677|TRACE|Matched EDNDWX004463$ to target OU OU=Member Clients,DC=bodxxx,dc=loxxx
2021-01-01 10:47:06.5028|ERROR|An unhandled error occurred while processing the request for the password for EDNDWX004463 by user xxxxSystem.DirectoryServices.DirectoryServicesCOMException (0x8007202B): A referral was returned from the server.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at System.DirectoryServices.DirectorySearcher.FindOne()
   at Lithnet.Laps.Web.Directory.IsPrincipalInOu(Principal p, String ou) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Internal\Directory.cs:line 24
   at Lithnet.Laps.Web.Controllers.LapController.GetMatchingTargetOrNull(ComputerPrincipal computer) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 143
   at Lithnet.Laps.Web.Controllers.LapController.Get(LapRequestModel model) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 73

Many Thanks

Simon

**Comment by ryannewington** [comment]
Hi Simon

There's likely a typo in one of your target names. 

The error you are getting means the AD returned a message to stay it's not authoritative for the naming context provided. 

Ryan

**Comment by simonford99** [comment]
Hi Ryan

Many thanks. I had only updated one of the targets and left the other with generic information. I commented this out and all working.

Thank again

Simon
