### ISSUE TITLE
Error when expiring LAPS password

### ISSUE THREAD

**Issue by ryannewington** [lithnet/laps-web#5]
An unhandled error occurred while processing the request for the password for xxx by user administrator
System.FormatException: String was not recognized as a valid TimeSpan.
   at System.Globalization.TimeSpanParse.TimeSpanResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName)
   at System.Globalization.TimeSpanParse.TryParseTimeSpan(String input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.Parse(String input, IFormatProvider formatProvider)
   at Lithnet.Laps.Web.Controllers.LapController.UpdateTargetPasswordExpiry(TargetElement target, ComputerPrincipal computer) in d:\github\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 268
   at Lithnet.Laps.Web.Controllers.LapController.Get(LapRequestModel model) in d:\github\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 100

**Comment by lockkie0** [comment]
I have the same problem. How resolve it?

**Comment by ryannewington** [comment]
@lockkie0 what language and regional settings do you have on both the server and workstation

**Comment by lockkie0** [comment]
@ryannewington on both servers settings: 
Windows - Server 2019 
Display language - English (United States)
Region - Russia
Regional format - Russian (Russia)

I aslo have different settings Region and Regional format (English or Russian) on other servers

**Comment by ryannewington** [comment]
Hi @lockkie0,

The problem seems to be parsing the 'expire-after' attribute in the web.config file.

Can you check each target and let me know what the text string value is for this attribute?

```xml
<target name="OU=Workstation Managment,DC=dev1,dc=local" type="Container" expire-after="03:00:00">
```
