### ISSUE TITLE
Getting error while retriving password : n unhandled error occurred while processing the request for the password for PC---------- by user --------- System.Runtime.InteropServices.COMException (0x8000500C): Unknown error (0x8000500c)

### ISSUE THREAD

**Issue by elesh27** [lithnet/laps-web#6]
2019-02-23 10:54:54.9675|ERROR|An unhandled error occurred while processing the request for the password for PC---------- by user --------- System.Runtime.InteropServices.COMException (0x8000500C): Unknown error (0x8000500c)
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at Lithnet.Laps.Web.Controllers.LapController.SetExpiryTime(DirectoryEntry d, DateTime newDateTime) in d:\github\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 277
   at Lithnet.Laps.Web.Controllers.LapController.UpdateTargetPasswordExpiry(TargetElement target, ComputerPrincipal computer) in d:\github\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 272
   at Lithnet.Laps.Web.Controllers.LapController.Get(LapRequestModel model) in d:\github\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 101

**Comment by ryannewington** [comment]
@elesh27 is the laps server joined to the domain? if it not, that's not a supported configuration.

If it is, then perhaps try clearing your ADSI schema cache. https://stackoverflow.com/a/24533535
Have you rebooted the LAPS server since adding the LAPS schema to AD?

**Comment by ryannewington** [comment]
Hi @elesh27 

please feel free to reopen this issue if you need additional assistance.

Ryan
