### ISSUE TITLE
The required anti-forgery form field "__RequestVerificationToken" is not present. 

### ISSUE THREAD

**Issue by benclaussen1** [lithnet/laps-web#7]
I am receiving this error when I request a password for a computer (I turned off custom errors to see it)... It worked **once** and retrieved a password, but that's it. It does not matter what I enter for a computer name.
![image](https://user-images.githubusercontent.com/46791633/54758531-bab9fb00-4bc2-11e9-97ee-7b5fb8b6a46a.png)

Some Googling led me to [StackOverflow](https://stackoverflow.com/questions/16102957/the-required-anti-forgery-form-field-requestverificationtoken-is-not-present)... I checked the source code and it seems to follow the suggested patterns. I also do not have "require SSL" enabled, or SSL cookies enabled in `web.config`. However, any combination of those make no difference. 

My website/server:
- Server 2012R2
- .NET Framework 4.7.2
- Single IP:443 binding with a hostname and valid certificate
- Windows authentication
- Deleted and re-created website and application pools

App pool:
- running under the account which has read permissions on the AD attribute
- .NET CLR Version v4.0.30319
- ![image](https://user-images.githubusercontent.com/46791633/54761796-2bfcac80-4bc9-11e9-9657-ba53e1fd1e09.png)

When I watch the requests using developer tools, the form field appears to be sent with the form:
![image](https://user-images.githubusercontent.com/46791633/54759749-1c7b6480-4bc5-11e9-8c50-63dbdddabed3.png)
![image](https://user-images.githubusercontent.com/46791633/54759756-200eeb80-4bc5-11e9-832a-d57863eb90eb.png)

One thing I noticed which may be completely unrelated: the cookie and form fields `__RequestVerificationToken` do not match, and is not set for SSL:
![image](https://user-images.githubusercontent.com/46791633/54760494-93fdc380-4bc6-11e9-83d9-2928e25a358a.png)
![image](https://user-images.githubusercontent.com/46791633/54760501-96f8b400-4bc6-11e9-89ea-14e7a2871eeb.png)

For fun, I cleared the cookie before submitting the form, and the error changed to `The required anti-forgery cookie "__RequestVerificationToken" is not present.`

Any ideas to resolve?

Full error from Application Log:
```
Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 3/21/2019 10:33:06 AM 
Event time (UTC): 3/21/2019 2:33:06 PM 
Event ID: f8fdd95005f44e87ba0ec33edd8cf12d 
Event sequence: 32 
Event occurrence: 3 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/14/ROOT-1-131976522215591254 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: D:\LAPS\Release-1.0.6763\ 
    Machine name: REDACTED
 
Process information: 
    Process ID: 4512 
    Process name: w3wp.exe 
    Account name: REDACTED
 
Exception information: 
    Exception type: HttpAntiForgeryException 
    Exception message: The required anti-forgery form field "__RequestVerificationToken" is not present.
   at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__0(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_0(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_0(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 
 
Request information: 
    Request URL: https://REDACTED:443/Lap/Get 
    Request path: /Lap/Get 
    User host address: REDACTED
    User: REDACTED 
    Is authenticated: True 
    Authentication Type: Negotiate 
    Thread account name: REDACTED
 
Thread information: 
    Thread ID: 7 
    Thread account name: REDACTED
    Is impersonating: False 
    Stack trace:    at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__0(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_0(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_0(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

```

**Comment by ryannewington** [comment]
Hi @benclaussen1 ,

It looks like something is tampering with the anti-forgery token. It's a pretty simple mechanism, not a lot can go wrong with it unless something is getting in the way. Eg browser plugins for perhaps a proxy of some sort.

Have you tried a plugin-less browser? Do you have a proxy or any other machinery in between your client and server that could be having an impact here?

**Comment by benclaussen1** [comment]
Welp... not a browser plugin but an IIS module. Something about the [Modsecurity IIS module](https://stackoverflow.com/a/36174875) was messing it up. I disabled the module for this website and its working now... No idea what about it actually caused the issue and not worth figuring it out since I don't need it for this site.

Thanks!
